name: NestJS CI/CD

on:
  push:
    branches: [ main ] # Se activa al subir a la rama main
  pull_request:
    branches: [ main ] # Se activa al crear un PR

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Usamos un servidor Linux virtual
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Descarga el codigo del repositorio
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Versión de Node
          cache: 'npm'
          
      - name: Instalar dependencias
        run: npm install
        
      - name: Correr tests unitarios
        run: npm run test
        
      - name: Correr tests e2e
        run: npm run test:e2e
        env:
          MONGODB_URI: mongodb://localhost:27017/test

      - name: Start NestJS App in background
        run: npm run start & # Lo corremos de fondo para que k6 pueda atacarlo
        env:
          MONGO_URI: mongodb://localhost:27017/test_db
          PORT: 3000

      - name: Wait for NestJS to be ready
        run: npx wait-on http://localhost:3000/users --timeout 30000

      - name: Setup k6
        uses: grafana/setup-k6-action@v1 # Configura k6 para pruebas de carga

      - name: Correr tests de carga con K6
        run: k6 run load-test.js